# Generated by Django 3.1.7 on 2021-03-28 07:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, max_length=30, null=True)),
                ('payment_type', models.CharField(choices=[('CS', 'Cash'), ('CR', 'Card')], default='CS', max_length=2)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
