# Generated by Django 3.1.7 on 2021-03-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210328_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='tags',
            field=models.CharField(choices=[('GR', 'Grocery'), ('MN', 'Medicine'), ('FD', 'Food'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
