# Generated by Django 3.1.7 on 2021-03-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_expense_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='tags',
            field=models.CharField(choices=[('GR', 'Grocery'), ('MN', 'Medicine'), ('FD', 'Food'), ('TL', 'Travel'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
