# Generated by Django 3.1.7 on 2021-03-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210329_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='tags',
            field=models.CharField(choices=[('GROCERY', 'Grocery'), ('MEDICINE', 'Medicine'), ('FOOD', 'Food'), ('TRAVEL', 'Travel'), ('CLOTHING', 'Clothing'), ('HOBBY', 'Hobby'), ('RESTAURANT', 'Restaurant'), ('UTILITY', 'Utility'), ('PERSONAL', 'Personal'), ('EDUCATION', 'Education'), ('ENTERTAINMENT', 'Entertainment'), ('OTHER', 'Other')], default='OTHER', max_length=15),
        ),
    ]
